### ISSUE TITLE
Improve "select all" visuals

### ISSUE THREAD

**Issue by thdoan** [kazzkiq/CodeFlask#140]
When you select all text, it doesn't look very good:

![image](https://github.com/kazzkiq/CodeFlask/assets/4110567/158e547d-f1da-42fb-970b-d05a4d9ada12)

I think this has to do with how the component is designed, with two layers of text on top of each other. Can this be improved?

**Comment by jonpyt** [comment]
Shameless plug, but since CodeFlask hasn't been maintained for years, you should consider using [Prism code editor](https://github.com/FIameCaster/prism-code-editor) instead. It's maintained and offers slightly better performance, more features, a smaller bundle size and many optional extensions.

If you want to stick with CodeFlask, this is an easy fix. Just make the `color` on the textarea's selection transparent. This works since the syntax highlighted code has a higher `z-index`.

```css
.codeflask__textarea::selection {
    background: hsl(210, 100%, 85%);
    color: transparent;
}
```
